# example sweetpotato build script

sweetpotato:
  build:
    - echo: hello world!
    - db: 
        type: sweetpotato
        path: build.yaml
        run:
          - read: 
              root: numbers
              target: echoRow
              fields: 
                id: numberNumeral
                name: numberName
    - echo: done!

  setRange:
    - property: {'name':range,'value':100}

  range:
    - include: setRange
    - run: {'target':build, 'range':'{{range}}'}

  echo:
    - echo: [1, 2, 3, 4, 5, 6, 7, 8, 9]

  bad:
    run: {'echo': test}
    echo:
       value: [1, 2, 3]
       echo: hello

  echoRow:
    - echo: '{{numberNumeral}} = {{numberName}}'

numbers: 
  - {'id':1,'name':one}
  - {'id':2,'name':two}
  - {'id':3,'name':three}
  - {'id':4,'name':four}
  - {'id':5,'name':five}

