#""""""""""""""""""""""""""""""
#  = example sweetpotato build script =
#...

sweetpotato:
    example:
      - echo: this is an example target
      - require: settokens
      - echo: tokens are go
      - echo: "sweetpotato will count from 0 to {{countto}} -1"
      - do: {"target": echocount, "range":"{{countto}}", "settoken":iteration}
      - echo: sweetpotato makes counting easy!
      - db:
          type: sweetpotato
          path: build.yaml
          read:
              root: somedata
              target: echomood
              do:
                  - echo: I am a nested echo task nested in-line inside a do task!
                  - echo: this part has mutex
                  - fields:
                      name: personName
                      mood: personMood

    settokens:
        - token:
            countto: 5

    echocount:
        - echo: "{{iteration}}"

    echomood:
        - echo: "{{personName}} is feeling {{personMood}}"

#"""""""""""""""""""""""""""""""
#  = targets for lock tests =
#  i.e. `sp longerrun & sleep 3; sp sayhello; sp longrun`
#  in the above example sayhello should finish first, then longerrun, then longrun
#...

    longrun: 
        - lock: 
            key: locktest
            do:
                - do: {"target": donothing, "range": 1000, "settoken":iteration}
                - echo: done longrun 
    longerrun: 
        - lock: 
            key: locktest
            do:
                - do: {"target": donothing, "range": 100000, "settoken":iteration}
                - echo: done longerrun 
    sayhello:
        - echo: why, hello there!

    donothing:

#""""""""""""""""""""""""""""""
#  = targets for workfile tests =
#...

    buildsh:
        workfile:
            path: my.sh
            backup: save
            lock:
                - write: "#/!bin/sh"
                - write: echo "hello world!" 

#""""""""""""""""""""""""""""""
#  = targets for xhtml tests =
#...

    publish:
       - token:
            wikiUrl: "http://localhost/mywiki"
            buildDir: "/tmp/build"
       - do:
            target: publishfromwiki

    publishfromwiki:
       - db:
            type: moincategory
            url: "{{wikiUrl}}/CategoryPublish"
            read:
                target: parsepage
                fields:
                    title: pageTitle 
                    url: pageUrl
                    name: pageName 

    parsepage:
        - extension: 
            name: www
            from: [sweetpotato,extensions]
        - www:
            url: "{{pageUrl}}"
            select:
                pageContent: "#content"
        - www:
            url: "{{wikiUrl}}/SideBar"
            select:
                sidebarContent: "#content"
        - do:
                target: buildpage
                
    buildpage:
       - extension: 
            name: xhtml
            from: [sweetpotato,extensions]
       - lock:
            - workfile:
                path: "{{buildDir}}/{{pageName}}.html"
                overwrite: True
                xhtml:   
                    - head:
                        - title: "{{pageTitle}}"
                    - body:
                        - div:
                            id: main
                            do:
                                - div:
                                    id: content
                                    table:
                                        - tr:
                                            - td:
                                                value: "{{pageContent}}"
                                - div:
                                    id: sidebar
                                    value: "{{sidebarContent}}"
                                - div: 
                                    id: header
                                    do:
                                        - p: "my site"
                                - div:
                                    id: footer
                                    do:
                                        - p: "{{pageUrl}}"

#""""""""""""""""""""""""""""""
#  = Inline Data =
#...

somedata:
    - {"name":bob, "mood":happy}
    - {"name":ann, "mood":silly}
    - {"name":joe, "mood":sleepy}
    - {"name":tom, "mood":angry}
    - {"name":sue, "mood":mopey}
    - {"name":tim, "mood":curious}
    - {"name":ken, "mood":amorous}
    - {"name":don, "mood":coy}
    - {"name":mel, "mood":scared}

