# example sweetpotato build script

sweetpotato:
  build:
    - echo: hello world!
    - db: 
        type: sweetpotato
        path: build.yaml
        do:
          - read: 
              root: numbers
              target: echoRow
              do:
                - echo: {'value': reading}
                - fields: 
                    id: numberNumeral
                    name: numberName
    - echo: done!

  setRange:
    - echo: setting range
    - token: 
        start: 10
        step: 2
        stop: 40 

  range:
    - require: setRange
    - echo: 'start is {{start}}'
    - echo: 'stop is {{stop}}'
    - echo: 'step is {{step}}'
    - do: {'target':build, 'range':['{{start}}','{{stop}}']}

  range2:
    - do: {'target':iterate, 'settoken': iteration, 'range':'{{stop}}'}

  iterate:
    - echo: 'Iteration {{iteration}}'
    - do: build 

  echo:
    - echo: echo
    - echo: {'value':[1, 2, 3, 4, 5, 6, 7, 8, 9]}

  bad:
    - do: {'target': iterate, 'settoken':iteration, 'list': [aha, abba, abc]}
    - echo:
       value: [1, 2, 3]
       echo: hello

  echoRow:
    - echo: '{{numberNumeral}} = {{numberName}}'

numbers: 
  - {'id':1,'name':one}
  - {'id':2,'name':two}
  - {'id':3,'name':three}
  - {'id':4,'name':four}
  - {'id':5,'name':five}

