sweetpotato:
  build:
    - echo: hello world!
    - db: 
        type: sweetpotato
        path: /home/dk/work/sweetpotato/build.yaml
        run:
          - read: 
             root: numbers
             target: echoRow
             fields: 
               id: numberNumeral
               name: numberName
    - echo: done!

  setRange:
    - property: {'name':range,'value':100}

  range:
    - include: setRange
    - run: {'target':build, 'range':'{{range}}'}

  echo:
    - echo: nothing to replace here

  echoRow:
    - echo: '{{numberNumeral}} = {{numberName}}'

numbers: 
  - {'id':1,'name':one}
  - {'id':2,'name':two}
  - {'id':3,'name':three}
  - {'id':4,'name':four}
  - {'id':5,'name':five}

