# example sweetpotato build script

sweetpotato:
  build:
    - echo: hello world!
    - db: 
        type: sweetpotato
        path: build.yaml
        do:
          - read: 
              root: numbers
              target: echoRow
              do:
                - echo: {'value': reading}
                - fields: 
                    id: numberNumeral
                    name: numberName
    - echo: done!

  setRange:
    - echo: setting range
    - token: {'name':range,'value':100}

  range:
    - require: setRange
    - echo: 'rage is {{range}}'
    - run: {'target':build, 'range':'{{range}}'}

  echo:
    - echo: [1, 2, 3, 4, 5, 6, 7, 8, 9]

  bad:
    run: {'echo': test}
    echo:
       value: [1, 2, 3]
       echo: hello

  echoRow:
    - echo: '{{numberNumeral}} = {{numberName}}'

numbers: 
  - {'id':1,'name':one}
  - {'id':2,'name':two}
  - {'id':3,'name':three}
  - {'id':4,'name':four}
  - {'id':5,'name':five}

